### ISSUE TITLE
Многократное срабатывание afterTransition

### ISSUE THREAD

**Issue by artpolikarpov** [ai/transition-events#2]
Вот такой код вызовет событие трижды:

$(elem).css('transform', 'translate(-1000px, 0)').afterTransition(function (e) {console.log(e)}).afterTransition(function (e) {console.log(e)}).afterTransition(function (e) {console.log(e)});

Мне кажется нужно какой-то флаг проставлять для защиты от дурака.

**Comment by ai** [comment]
Точно так же `$(elem).click(callback).click(callback).click(callback)` будет срабатывать трижды по клику :).

Покажи реальный пример, где это создаёт проблему.

**Comment by artpolikarpov** [comment]
Наверное, проблемы это не создаёт :-)
