### ISSUE TITLE
Мне кажется, для вебкита поставлен неправильное значение свойства

### ISSUE THREAD

**Issue by h4** [ai/transition-events#3]
В https://github.com/ai/transition-events/blob/master/lib/transition-events.js#L37 указано "WebkitTransition", но в Chrome 23.0.1271.64 у document.body.styles нет такого свойства, есть только webkitTransition.

Это баг или фича?

**Comment by ai** [comment]
В Хроме работает оба варианта `webkitTransition` и `WebkitTransition`. В Firefox и Opera работает только вариант с большой буквы. Семантически верно именно с большой буквы (например, `line-height` → `lineHeight`, то есть буква перед дефисом становится большой, но браузерный префикс идёт сразу с дефисом вначале `-webkit-transition`, значит и первая буква будет сразу большой — `WebkitTransition`).

Так что я оставил более семантически верный, раз он нормально работает.
