### ISSUE TITLE
Add support for animationend

### ISSUE THREAD

**Issue by jscheel** [ai/transition-events#5]
Add support for animation events as well as transition events. Thanks for the library!

**Comment by ai** [comment]
Why you need it in this library? You can just call it from jQuery:

``` js
node.on 'animationend', ->
  animationIsFinished()
```

**Comment by jscheel** [comment]
Well, yes, but the same can be said for transistionend. What's the difference?

**Comment by ai** [comment]
Because, `transitionend` needed vendor prefix.

**Comment by jscheel** [comment]
Does animationend not need any vendor prefixes anymore? I didn't realize
that. Either way, you still provide a good wrapping for chaining etc. that
would benefit from animationend as well.

**Comment by ai** [comment]
But API in transition events will be like:

``` coffee
node.afterAnimation ->
```

which very closer to:

``` coffee
node.on 'animationend', ->
```

So, this API willn’t shortcut anything :).
