### ISSUE TITLE
Please add an afterTransitionS

### ISSUE THREAD

**Issue by stevenvachon** [ai/transition-events#6]
I'm writing an app using an MVC library similar to AngularJS. When it removes elements, it does not use `jQuery.remove()` because it rewrites the `innerHTML` instead.

Now, I have multiple transitions on an element. Using `afterTransition`, I update my view model which removes the element. jQuery then runs many more `afterTransition`s even though the element has been removed, resulting in errors.

If we had a `afterTransitions`, this error could be avoided. All you'd have to do is grab the sum of the durations and delays.

**Comment by stevenvachon** [comment]
Here's what I mocked up. It works:

``` javascript
afterTransitions: function (durationPart, callback) {
    if ( typeof(callback) == 'undefined' ) {
        callback     = durationPart;
        durationPart = 1;
    }

    if ( !$.Transitions.isSupported() ) {
        for (var i = 0; i < this.length; i++) {
            callback.call(this[i], {
                type:          'aftertransition',
                elapsedTime:   0,
                propertyName:  '',
                currentTarget: this[i]
            });
        }
        return this;
    }

    for (var i = 0; i < this.length; i++) {
        var el = $(this[i]);
        var props     = el.css('transition-property').split(/,\s*/);
        var durations = el.css('transition-duration');
        var delays    = el.css('transition-delay');

        durations = $.Transitions._parseTimes(durations);
        delays    = $.Transitions._parseTimes(delays);

        var duration, delay, after, elapsed, total=0;
        for (var j = 0; j < props.length; j++) {
            duration = durations[ durations.length == 1 ? 0 : j ];
            delay    = delays[ delays.length == 1 ? 0 : j ];
            total   += duration + delay;
        }

        after   = total * durationPart;
        elapsed = after / 1000;

        (function (el, elapsed) {
          setTimeout(function () {
              $.Transitions.animFrame(function () {
                callback.call(el[0], {
                    type:          'aftertransitions',
                    elapsedTime:   elapsed,
                    currentTarget: el[0]
                });
              });
          }, after);
        })(el, after, elapsed);
    }
    return this;
},
```

**Comment by ai** [comment]
Hm, nice idea. But I don’t really support this library now (because I can’t detect that transition was canceled :( )

**Comment by stevenvachon** [comment]
Yeah, hopefully they'll add an event in the future to handle that.

What do you use now? Transit?

**Comment by ai** [comment]
Just hardcode time and check property manually :D

**Comment by stevenvachon** [comment]
Yeah, that's what I'm trying to avoid because it merges the view and the controller too much (MVC)

**Comment by ai** [comment]
Yeap, me too :). I will be happy to have time to find some hack for fix `transition-events` :).

**Comment by stevenvachon** [comment]
I've created a plugin with this functionality. It'll probably make your development easier as you won't need to manually put in timeout values:
https://github.com/stevenvachon/jquery.transitionsend

**Comment by ai** [comment]
Nice! :)

**Comment by ai** [comment]
BTW, most of browsers doesn’t require prefix now: [Can I Use page](http://caniuse.com/css-transitions)

**Comment by stevenvachon** [comment]
Yep, my plugin does have `transitionend` code in it, but I commented it out for that very reason.

`transitionsend` is different (notice the "s") :)
