### ISSUE TITLE
How do we remove an event listener?

### ISSUE THREAD

**Issue by stevenvachon** [ai/transition-events#7]
To avoid memory leaks when removing the element through innerHTML modifications with handlebars/mustache

**Comment by ai** [comment]
Can you use `afterTransition`? It doesn’t create listener, only timeout.

**Comment by ai** [comment]
Unfortunately, I disappointed current `transition-event` reallization and didn’t support library right now :(.

**Comment by stevenvachon** [comment]
Oh, actually, I _am_ using `afterTransition`. Is it possible to clear its timeout from memory, though?

You really should consider moving forward with this plugin; it works very well! Here's an example of how I'm using it:
http://jsfiddle.net/cCZnE/6/

**Comment by ai** [comment]
You can just wait time, and after tranition time timeouts will be destoied.

**Comment by stevenvachon** [comment]
Oh, okay, cool. Then it's all done, basically; except for the `afterTransitionS` function (that I hacked together) hehe ;)
